#!/usr/bin/env bash
# ig-download.sh — Download Instagram CDN assets with proper headers and retry
# Part of astro-static pipeline: used by instagram-extractor to download images
# from Instagram CDN URLs before they expire (signed URLs last ~24h).
#
# Usage: ig-download.sh <cdn_url> <output_path> [--referer URL]
#
# Handles: Referer header requirement (Instagram blocks requests without it),
# User-Agent rotation (mobile-first for better CDN cache hits), retry with
# exponential backoff, output validation (must be a real image, not an error page).

set -euo pipefail

CDN_URL="${1:?Usage: ig-download.sh <cdn_url> <output_path> [--referer URL]}"
OUTPUT="${2:?Usage: ig-download.sh <cdn_url> <output_path> [--referer URL]}"
REFERER="https://www.instagram.com/"

# Parse optional --referer flag
if [ $# -ge 4 ] && [ "$3" = "--referer" ]; then
    REFERER="$4"
fi

# Restrict writes to the Instagram pipeline subtree before validating remote
# URLs, creating directories, or invoking curl. The output path is normally
# generated by instagram-extractor, but this script is still a write-side
# boundary and must reject traversal, absolute paths, and unrelated project
# paths first.
python3 - "$OUTPUT" <<'PY'
from pathlib import PurePosixPath
import sys

output = sys.argv[1]
path = PurePosixPath(output)
parts = path.parts
allowed = (
    len(parts) > 3
    and parts[0] == 'pipeline'
    and parts[1] == '00-instagram'
    and parts[2] in {'assets', 'highlights'}
)
if not output or output.startswith('~') or path.is_absolute() or '..' in parts or not allowed:
    print(f"STATUS:IG_DOWNLOAD_FAILED reason=unsafe_output_path output={output}", file=sys.stderr)
    raise SystemExit(1)
PY

# Validate the remote URL before creating output paths or invoking curl. The
# URL comes from extracted Instagram data, so it must not be allowed to turn the
# control node into an SSRF client. We allow only HTTPS Instagram/Facebook CDN
# hosts, reject private/loopback/link-local resolutions, and never log query
# strings or fragments (signed CDN URLs may contain sensitive tokens).
SAFE_URL=$(python3 - "$CDN_URL" <<'PY'
from urllib.parse import urlparse
import ipaddress
import socket
import sys

url = sys.argv[1]
parsed = urlparse(url)
host = (parsed.hostname or '').lower().rstrip('.')
scheme = parsed.scheme.lower()
safe = f"{scheme or '<missing-scheme>'}://{host or '<missing-host>'}{parsed.path or '/'}"

def fail(reason: str) -> None:
    print(f"STATUS:IG_DOWNLOAD_FAILED reason=unsafe_url detail={reason} url={safe}", file=sys.stderr)
    raise SystemExit(1)

if scheme != 'https':
    fail('scheme')
if not host:
    fail('host')
if parsed.username or parsed.password:
    fail('userinfo')

allowed = (
    host == 'cdninstagram.com'
    or host.endswith('.cdninstagram.com')
    or host == 'fbcdn.net'
    or host.endswith('.fbcdn.net')
    or host == 'instagram.com'
    or host.endswith('.instagram.com')
)
if not allowed:
    fail('host')

try:
    ip_candidates = [ipaddress.ip_address(host)]
except ValueError:
    try:
        infos = socket.getaddrinfo(host, None, proto=socket.IPPROTO_TCP)
    except socket.gaierror:
        fail('resolution')
    ip_candidates = []
    for info in infos:
        try:
            ip_candidates.append(ipaddress.ip_address(info[4][0]))
        except ValueError:
            fail('resolution')

if not ip_candidates:
    fail('resolution')
for ip in ip_candidates:
    if ip.is_private or ip.is_loopback or ip.is_link_local or ip.is_reserved or ip.is_multicast or ip.is_unspecified:
        fail('private_ip')

print(safe)
PY
)

# Ensure output directory exists
mkdir -p "$(dirname "$OUTPUT")"

# Mobile-first User-Agent rotation — Instagram CDN serves better quality to
# mobile UAs and caches them more aggressively.
USER_AGENTS=(
    "Mozilla/5.0 (iPhone; CPU iPhone OS 17_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Mobile/15E148 Safari/604.1"
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
    "Mozilla/5.0 (iPhone; CPU iPhone OS 17_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/126.0.6478.153 Mobile/15E148 Safari/604.1"
)

# Rotate UA per invocation for diversity
UA="${USER_AGENTS[$((RANDOM % ${#USER_AGENTS[@]}))]}"

# Download with retry (max 3 attempts, 2s/4s/8s backoff)
MAX_RETRIES=3
for attempt in $(seq 1 $MAX_RETRIES); do
    if curl -sS \
        -H "Referer: $REFERER" \
        -H "User-Agent: $UA" \
        -H "Accept: image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8" \
        -H "Accept-Language: en-US,en;q=0.9" \
        -H "Sec-Fetch-Dest: image" \
        -H "Sec-Fetch-Mode: no-cors" \
        -H "Sec-Fetch-Site: cross-site" \
        -o "$OUTPUT" \
        --max-time 30 \
        --connect-timeout 10 \
        --proto '=https' \
        --max-redirs 0 \
        "$CDN_URL" 2>/dev/null; then

        # Verify we got an actual image, not an error/redirect page
        if [ -s "$OUTPUT" ] && file "$OUTPUT" | grep -qE 'JPEG|PNG|WebP|GIF|SVG'; then
            # Check minimum size (1KB — anything smaller is likely an error page)
            SIZE=$(stat -f%z "$OUTPUT" 2>/dev/null || stat -c%s "$OUTPUT" 2>/dev/null || echo 0)
            if [ "$SIZE" -ge 1024 ]; then
                exit 0
            fi
        fi
        # File exists but isn't a valid image — retry
        rm -f "$OUTPUT"
    fi

    if [ "$attempt" -lt "$MAX_RETRIES" ]; then
        BACKOFF=$((2 ** attempt))  # 2, 4, 8 seconds
        sleep "$BACKOFF"
    fi
done

# All retries exhausted
echo "STATUS:IG_DOWNLOAD_FAILED url=$SAFE_URL output=$OUTPUT" >&2
exit 1
